#     GNU GPLv3
#
#     Copyright (C) 2025  Marco Manfrini
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#     mnfmrc@unife.it

# PATH ----

baseDir="/home/imer/works/DARIO"
tablesDir=paste0(baseDir,"/tables")
redcapDir=paste0(baseDir,"/redcap")
cedapDir=paste0(baseDir,"/cedap/2023")
sdoDir="/home/imer/works/algo_sdo/stage_12"
sdoDirMerge="/home/imer/works/algo_sdo/export"
exportDir=paste0(baseDir,"/export")
stage0Dir=paste0(baseDir,"/stage_0")
stage1Dir=paste0(baseDir,"/stage_1")
stage2Dir=paste0(baseDir,"/stage_2")
stage3Dir=paste0(baseDir,"/stage_3")
stage4Dir=paste0(baseDir,"/stage_4")
stage5Dir=paste0(baseDir,"/stage_5")

# PACKAGES ----

library(tidyverse)
library(readxl)

# GLOBAL VARS ----

## Cohort date of birth ----
Year = 2023

## Files ----

rcFileName <- "IMERTEST-Coorte2023_DATA_2025-08-04_1605.csv"
rcRFileName <- "preprocess_edc.r"
cedapFileName <- "cedap_plus_2023.csv"
sdoFileName <- "sdo_stage_11b_clinical_rev_export_final.xlsx"
sdoFileNameMerge <- "sdo_stage12_transcode_export.csv"

## stage_2 variables list ----

stage_2_vars_list <- c(
  "record_id",	
  "redcap_data_access_group",
  "birth_date",
  "centre",
  "numloc",	
  "sdo_number",
  "gestlength",	
  "nbrbaby",
  "sp_twin",
  "nbrmalf",
  "sex",
  "type",	
  "civreg",
  "weight",
  "survival",
  "death_date",
  "mocitizenship",
  "resmo",
  "extra_er_resmo",
  "datemo",	
  "agemo",	
  "bmi",	
  "totpreg",
  "whendisc",	
  "agedisc",	
  "condisc",
  "firstpre",
  "sp_firstpre",
  "karyo",
  "sp_karyo",	
  "gentest",
  "sp_gentest",	
  "surgery",
  "pm",
  "pm_notes",
  "presyn",
  "premal1",
  "premal2",
  "premal3",
  "premal4",
  "premal5",
  "premal6",
  "premal7",
  "premal8",
  "imer_key",
  "syndrome",
  "syndrome_desc_detail",
  "sp_syndrome",
  "omim",
  "orpha",
  "malfo1",
  "malfo1_desc_detail",
  "sp_malfo1",
  "malfo2",
  "malfo2_desc_detail",
  "sp_malfo2",
  "malfo3",
  "malfo3_desc_detail",
  "sp_malfo3",
  "malfo4",
  "malfo4_desc_detail",
  "sp_malfo4",
  "malfo5",	
  "malfo5_desc_detail",
  "sp_malfo5",
  "malfo6",
  "malfo6_desc_detail",
  "sp_malfo6",
  "malfo7",
  "malfo7_desc_detail",
  "sp_malfo7",
  "malfo8",
  "malfo8_desc_detail",
  "sp_malfo8",
  "assconcept",
  "agefa",
  "socf",
  "occupmo",
  "matdiab",
  "illbef1",
  "sp_illbef1",
  "icd10illbef1",
  "illbef2",
  "sp_illbef2",
  "icd10illbef2",
  "illdur1",
  "sp_illdur1",
  "icd10illdur1",
  "illdur2",
  "sp_illdur2",
  "icd10illdur2",
  "folic_g14",
  "extra_drugs",
  "firsttri",
  "drugs1",
  "sp_ifnotlisted_medication",
  "sp_drugs",
  "drugs2",
  "sp_ifnotlisted_medication_2",
  "sp_drugs_2",
  "drugs3",
  "sp_ifnotlisted_medication_3",
  "sp_drugs_3",
  "drugs4",
  "sp_ifnotlisted_medication_4",
  "sp_drugs_4",
  "drugs5",
  "sp_ifnotlisted_medication_5",
  "sp_drugs_5",
  "inf_cov_test",
  "imm_cov_test",
  "oth_cov_test",
  "sp_oth_cov_test",
  "start_cov",
  "cov_severity",
  "consang",
  "sp_consang",
  "sibanom",
  "sp_sibanom",
  "prevsib",
  "sib1",
  "sib2",
  "sib3",
  "moanom",
  "sp_moanom",
  "faanom",
  "sp_faanom",
  "matedu",
  "socm",
  "migrant",
  "genrem",
  "syndrome.factor",
  "malfo1.factor",
  "malfo2.factor",
  "malfo3.factor",
  "malfo4.factor",
  "malfo5.factor",
  "malfo6.factor",
  "malfo7.factor",
  "malfo8.factor",
  "cohort",
  "birthCenter",
  "data_source",
  "cedap_linked"
)

eurocat_vars_list <- c(
  "record_id",	
  "birth_date",
  "centre",
  "numloc",	
  "sdo_number",
  "gestlength",	
  "nbrbaby",
  "sp_twin",
  "nbrmalf",
  "sex",
  "type",	
  "civreg",
  "weight",
  "survival",
  "death_date",
  "mocitizenship",
  "resmo",
  "extra_er_resmo",
  "datemo",	
  "agemo",	
  "bmi",	
  "totpreg",
  "whendisc",	
  "agedisc",	
  "condisc",
  "firstpre",
  "sp_firstpre",
  "karyo",
  "sp_karyo",	
  "gentest",
  "sp_gentest",	
  "surgery",
  "pm",
  "pm_notes",
  "presyn",
  "premal1",
  "premal2",
  "premal3",
  "premal4",
  "premal5",
  "premal6",
  "premal7",
  "premal8",
  "imer_key",
  "syndrome",
  "sp_syndrome",
  "omim",
  "orpha",
  "malfo1",
  "sp_malfo1",
  "malfo2",
  "sp_malfo2",
  "malfo3",
  "sp_malfo3",
  "malfo4",
  "sp_malfo4",
  "malfo5",	
  "sp_malfo5",
  "malfo6",
  "sp_malfo6",
  "malfo7",
  "sp_malfo7",
  "malfo8",
  "sp_malfo8",
  "assconcept",
  "agefa",
  "socf",
  "occupmo",
  "matdiab",
  "illbef1",
  "sp_illbef1",
  "illbef2",
  "sp_illbef2",
  "illdur1",
  "sp_illdur1",
  "illdur2",
  "sp_illdur2",
  "folic_g14",
  "extra_drugs",
  "firsttri",
  "drugs1",
  "sp_drugs",
  "drugs2",
  "sp_drugs_2",
  "drugs3",
  "sp_drugs_3",
  "drugs4",
  "sp_drugs_4",
  "drugs5",
  "sp_drugs_5",
  "inf_cov_test",
  "imm_cov_test",
  "oth_cov_test",
  "sp_oth_cov_test",
  "start_cov",
  "cov_severity",
  "consang",
  "sp_consang",
  "sibanom",
  "sp_sibanom",
  "prevsib",
  "sib1",
  "sib2",
  "sib3",
  "moanom",
  "sp_moanom",
  "faanom",
  "sp_faanom",
  "matedu",
  "socm",
  "migrant",
  "genrem",
  "data_source",
  "prog_paz_neo",
  "cedap_linked",
  "cod_pres",
  "amniocentesis",
  "chorvilsam",
  "ultrason",
  "mo_smoking",
  "mo_alcohol",
  "pre_sa",
  "pre_topfa",
  "pre_live",
  "pre_still"
)

cedap_linked_vars <- c(
  "prog_paz_neo",
  "prog_paz_m",
  "COD_PRES",
  "AMNIOCENTESI",
  "VILLOCENTESI",
  "ECOGRAFIA_OLTRE22SETTIMANE",
  "PESO",
  "CIRCONFERENZA_CRANICA",
  "PESO_MADRE_PREGRAVIDICO",
  "ALTEZZA_MADRE",
  "NUMERO_ABORTI_SPONTANEI",
  "NUMERO_IVG",         
  "NUMERO_NATI_VIVI",
  "NUMERO_NATI_MORTI",
  "metodi_PMA",
  "ABITUDINE_AL_FUMO"
)

